apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftp-pv
  #namespace: mc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.15
    path: /var/nfs