apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-pv
  labels:
    name: node-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 25Gi
  storageClassName: standard
  hostPath:
    path: /pv